-- GENERATED by bin/build.py from checks/registry.csv and
-- checks/postgres/checks/*.sql. Do not hand-edit: run bin/build.py.
--
-- Pass: deep, scope: database. 0 check(s), run in priority order so that if the run
-- is cut short the worst findings are already in hand.
--
-- Run it directly:
--     psql "$DSN" -X -q -f deep-database.sql --csv > triage.csv 2>&1
--
-- Every check is bracketed by `@@CHECK <id>` and `@@END <id>` markers and
-- returns the same six columns: check_id, scope, object, details,
-- evidence_json, confidence. Checks that do not apply to this server version
-- or to this node's role print `@@SKIP <id> <reason>` instead of running.
--
-- ON_ERROR_STOP is deliberately off: a privilege error on one check must not
-- abandon the rest of the run. Errors appear on stderr next to their marker.

\set ON_ERROR_STOP off
\set QUIET on
\pset pager off

-- ---- session safety (from 01_session.sql) ----
-- db-triage session safety block. Source this before every batch of checks.
--
-- This file is the enforcement point for the read-only contract. Nothing in
-- db-triage may mutate data, schema, or server state; these SETs make the
-- session refuse to even if a check were wrong.
--
-- Optional caller-supplied variables (psql -v):
--   db_triage_statement_timeout   default '10s'  ('60s' for the deep pass)
--   db_triage_lock_timeout        default '2s'
--   db_triage_version             default '0.1.0'

\if :{?db_triage_version}
\else
\set db_triage_version '0.1.0'
\endif
\if :{?db_triage_statement_timeout}
\else
\set db_triage_statement_timeout '10s'
\endif
\if :{?db_triage_lock_timeout}
\else
\set db_triage_lock_timeout '2s'
\endif

-- Identifiable: the DBA can see and cancel this run in pg_stat_activity.
\set db_triage_app_name 'db-triage/':db_triage_version
SET application_name = :'db_triage_app_name';

-- Read-only: every statement runs in a read-only transaction.
SET default_transaction_read_only = on;

-- Bounded: no statement runs unbounded, and no catalog read queues behind DDL.
SET statement_timeout = :'db_triage_statement_timeout';
SET lock_timeout = :'db_triage_lock_timeout';
SET idle_in_transaction_session_timeout = '60s';

-- Quiet and cheap: no JIT compilation for catalog queries, no NOTICE spam.
SET client_min_messages = warning;
SET jit = off;

-- Deterministic output for the parser.
SET DateStyle = 'ISO, YMD';
SET bytea_output = 'hex';

-- ---- threshold defaults (from lib/thresholds.sql) ----
-- GENERATED by bin/build.py from checks/registry.csv and
-- checks/postgres/checks/*.sql. Do not hand-edit: run bin/build.py.

-- Default value for every overridable threshold used by the checks.
-- Variable name = lower(check_id) with '-' replaced by '_', then '_' + the
-- threshold key. A value supplied with `psql -v name=value` wins over the
-- default below, which is how .db-triage.yml overrides reach the SQL.

-- PG-BAK-003
\if :{?pg_bak_003_ready_files}
\else
\set pg_bak_003_ready_files 10
\endif
\if :{?pg_bak_003_stall_seconds}
\else
\set pg_bak_003_stall_seconds 3600
\endif

-- PG-BAK-008
\if :{?pg_bak_008_backup_age_days}
\else
\set pg_bak_008_backup_age_days 7
\endif

-- PG-CAP-001
\if :{?pg_cap_001_used_fraction}
\else
\set pg_cap_001_used_fraction 0.90
\endif

-- PG-CORR-005
\if :{?pg_corr_005_scan_bytes}
\else
\set pg_corr_005_scan_bytes 52428800
\endif

-- PG-REPL-002
\if :{?pg_repl_002_retained_bytes}
\else
\set pg_repl_002_retained_bytes 10737418240
\endif

-- PG-WRAP-001
\if :{?pg_wrap_001_xid_age}
\else
\set pg_wrap_001_xid_age 1500000000
\endif

-- PG-CONN-001
\if :{?pg_conn_001_conn_fraction}
\else
\set pg_conn_001_conn_fraction 0.90
\endif

-- PG-LOCK-006
\if :{?pg_lock_006_prepared_seconds}
\else
\set pg_lock_006_prepared_seconds 3600
\endif

-- PG-REPL-003
\if :{?pg_repl_003_retained_bytes}
\else
\set pg_repl_003_retained_bytes 1073741824
\endif
\if :{?pg_repl_003_retained_bytes_high}
\else
\set pg_repl_003_retained_bytes_high 10737418240
\endif

-- PG-REPL-006
\if :{?pg_repl_006_lag_bytes}
\else
\set pg_repl_006_lag_bytes 1073741824
\endif
\if :{?pg_repl_006_lag_seconds}
\else
\set pg_repl_006_lag_seconds 300
\endif

-- PG-REPL-008
\if :{?pg_repl_008_replay_gap_bytes}
\else
\set pg_repl_008_replay_gap_bytes 1073741824
\endif

-- PG-SCHEMA-001
\if :{?pg_schema_001_exhaustion_fraction}
\else
\set pg_schema_001_exhaustion_fraction 0.90
\endif

-- PG-LOCK-001
\if :{?pg_lock_001_blocked_seconds}
\else
\set pg_lock_001_blocked_seconds 300
\endif

-- PG-LOCK-003
\if :{?pg_lock_003_idle_seconds}
\else
\set pg_lock_003_idle_seconds 3600
\endif

-- PG-REL-005
\if :{?pg_rel_005_uptime_seconds}
\else
\set pg_rel_005_uptime_seconds 86400
\endif

-- PG-WRAP-002
\if :{?pg_wrap_002_xid_age}
\else
\set pg_wrap_002_xid_age 1000000000
\endif
\if :{?pg_wrap_002_xid_age_critical}
\else
\set pg_wrap_002_xid_age_critical 1500000000
\endif

-- PG-CAP-002
\if :{?pg_cap_002_used_fraction}
\else
\set pg_cap_002_used_fraction 0.80
\endif
\if :{?pg_cap_002_used_fraction_high}
\else
\set pg_cap_002_used_fraction_high 0.90
\endif

-- PG-CAP-003
\if :{?pg_cap_003_projection_days}
\else
\set pg_cap_003_projection_days 30
\endif
\if :{?pg_cap_003_min_snapshot_days}
\else
\set pg_cap_003_min_snapshot_days 7
\endif

-- PG-LOCK-005
\if :{?pg_lock_005_xact_seconds}
\else
\set pg_lock_005_xact_seconds 3600
\endif

-- PG-MEM-001
\if :{?pg_mem_001_shared_buffers_bytes}
\else
\set pg_mem_001_shared_buffers_bytes 134217728
\endif

-- PG-REL-011
\if :{?pg_rel_011_scan_bytes}
\else
\set pg_rel_011_scan_bytes 52428800
\endif

-- PG-WRAP-007
\if :{?pg_wrap_007_freeze_max_age}
\else
\set pg_wrap_007_freeze_max_age 1000000000
\endif

-- PG-BAK-009
\if :{?pg_bak_009_restore_test_days}
\else
\set pg_bak_009_restore_test_days 90
\endif

-- PG-CONN-002
\if :{?pg_conn_002_conn_fraction}
\else
\set pg_conn_002_conn_fraction 0.70
\endif
\if :{?pg_conn_002_conn_fraction_high}
\else
\set pg_conn_002_conn_fraction_high 0.90
\endif

-- PG-CONN-003
\if :{?pg_conn_003_max_conn}
\else
\set pg_conn_003_max_conn 500
\endif
\if :{?pg_conn_003_pooler_address_fraction}
\else
\set pg_conn_003_pooler_address_fraction 0.8
\endif
\if :{?pg_conn_003_pooler_address_count}
\else
\set pg_conn_003_pooler_address_count 3
\endif

-- PG-CONN-008
\if :{?pg_conn_008_waiting_sessions}
\else
\set pg_conn_008_waiting_sessions 10
\endif

-- PG-IDX-002
\if :{?pg_idx_002_min_bytes}
\else
\set pg_idx_002_min_bytes 1073741824
\endif
\if :{?pg_idx_002_stats_age_days}
\else
\set pg_idx_002_stats_age_days 30
\endif

-- PG-IDX-006
\if :{?pg_idx_006_bloat_pct}
\else
\set pg_idx_006_bloat_pct 50
\endif
\if :{?pg_idx_006_wasted_bytes}
\else
\set pg_idx_006_wasted_bytes 524288000
\endif
\if :{?pg_idx_006_top_n}
\else
\set pg_idx_006_top_n 10
\endif

-- PG-IDX-008
\if :{?pg_idx_008_min_bytes}
\else
\set pg_idx_008_min_bytes 104857600
\endif
\if :{?pg_idx_008_parent_writes}
\else
\set pg_idx_008_parent_writes 1000
\endif

-- PG-IDX-010
\if :{?pg_idx_010_min_bytes}
\else
\set pg_idx_010_min_bytes 1073741824
\endif
\if :{?pg_idx_010_min_seq_scans}
\else
\set pg_idx_010_min_seq_scans 100
\endif
\if :{?pg_idx_010_rows_per_scan}
\else
\set pg_idx_010_rows_per_scan 100000
\endif
\if :{?pg_idx_010_seq_fraction}
\else
\set pg_idx_010_seq_fraction 0.05
\endif
\if :{?pg_idx_010_top_n}
\else
\set pg_idx_010_top_n 10
\endif

-- PG-LOCK-002
\if :{?pg_lock_002_blocked_seconds}
\else
\set pg_lock_002_blocked_seconds 30
\endif
\if :{?pg_lock_002_blocked_seconds_high}
\else
\set pg_lock_002_blocked_seconds_high 300
\endif

-- PG-LOCK-004
\if :{?pg_lock_004_idle_seconds}
\else
\set pg_lock_004_idle_seconds 300
\endif
\if :{?pg_lock_004_idle_seconds_high}
\else
\set pg_lock_004_idle_seconds_high 3600
\endif

-- PG-MEM-003
\if :{?pg_mem_003_ram_bytes}
\else
\set pg_mem_003_ram_bytes 0
\endif
\if :{?pg_mem_003_ram_fraction}
\else
\set pg_mem_003_ram_fraction 1.0
\endif

-- PG-REPL-004
\if :{?pg_repl_004_retained_bytes_low}
\else
\set pg_repl_004_retained_bytes_low 1073741824
\endif

-- PG-REPL-007
\if :{?pg_repl_007_lag_bytes}
\else
\set pg_repl_007_lag_bytes 104857600
\endif
\if :{?pg_repl_007_lag_seconds}
\else
\set pg_repl_007_lag_seconds 30
\endif
\if :{?pg_repl_007_lag_bytes_high}
\else
\set pg_repl_007_lag_bytes_high 1073741824
\endif
\if :{?pg_repl_007_lag_seconds_high}
\else
\set pg_repl_007_lag_seconds_high 300
\endif

-- PG-REPL-011
\if :{?pg_repl_011_conflicts_per_day}
\else
\set pg_repl_011_conflicts_per_day 100
\endif

-- PG-REPL-014
\if :{?pg_repl_014_flush_lag_seconds}
\else
\set pg_repl_014_flush_lag_seconds 1
\endif

-- PG-SCHEMA-002
\if :{?pg_schema_002_exhaustion_fraction}
\else
\set pg_schema_002_exhaustion_fraction 0.70
\endif
\if :{?pg_schema_002_exhaustion_fraction_high}
\else
\set pg_schema_002_exhaustion_fraction_high 0.90
\endif

-- PG-SEC-008
\if :{?pg_sec_008_min_connections}
\else
\set pg_sec_008_min_connections 5
\endif

-- PG-VAC-001
\if :{?pg_vac_001_duration_seconds}
\else
\set pg_vac_001_duration_seconds 21600
\endif

-- PG-VAC-002
\if :{?pg_vac_002_overdue_tables}
\else
\set pg_vac_002_overdue_tables 20
\endif

-- PG-VAC-003
\if :{?pg_vac_003_dead_multiple}
\else
\set pg_vac_003_dead_multiple 2
\endif
\if :{?pg_vac_003_min_dead_tuples}
\else
\set pg_vac_003_min_dead_tuples 100000
\endif
\if :{?pg_vac_003_min_bytes}
\else
\set pg_vac_003_min_bytes 104857600
\endif
\if :{?pg_vac_003_top_n}
\else
\set pg_vac_003_top_n 10
\endif

-- PG-VAC-004
\if :{?pg_vac_004_never_analyzed_rows}
\else
\set pg_vac_004_never_analyzed_rows 100000
\endif
\if :{?pg_vac_004_stale_fraction}
\else
\set pg_vac_004_stale_fraction 0.2
\endif
\if :{?pg_vac_004_stale_min_rows}
\else
\set pg_vac_004_stale_min_rows 1000000
\endif
\if :{?pg_vac_004_top_n}
\else
\set pg_vac_004_top_n 10
\endif

-- PG-VAC-005
\if :{?pg_vac_005_xmin_age}
\else
\set pg_vac_005_xmin_age 50000000
\endif

-- PG-VAC-006
\if :{?pg_vac_006_bloat_pct}
\else
\set pg_vac_006_bloat_pct 50
\endif
\if :{?pg_vac_006_wasted_bytes}
\else
\set pg_vac_006_wasted_bytes 1073741824
\endif
\if :{?pg_vac_006_min_bytes}
\else
\set pg_vac_006_min_bytes 1073741824
\endif
\if :{?pg_vac_006_top_n}
\else
\set pg_vac_006_top_n 10
\endif

-- PG-WAL-001
\if :{?pg_wal_001_min_checkpoints}
\else
\set pg_wal_001_min_checkpoints 20
\endif
\if :{?pg_wal_001_requested_ratio}
\else
\set pg_wal_001_requested_ratio 0.5
\endif

-- PG-WAL-006
\if :{?pg_wal_006_waldir_multiple}
\else
\set pg_wal_006_waldir_multiple 3
\endif
\if :{?pg_wal_006_waldir_floor_bytes}
\else
\set pg_wal_006_waldir_floor_bytes 53687091200
\endif

-- PG-WRAP-003
\if :{?pg_wrap_003_freeze_multiple}
\else
\set pg_wrap_003_freeze_multiple 1.5
\endif
\if :{?pg_wrap_003_xid_age_ceiling}
\else
\set pg_wrap_003_xid_age_ceiling 1000000000
\endif

-- PG-WRAP-004
\if :{?pg_wrap_004_top_n}
\else
\set pg_wrap_004_top_n 10
\endif
\if :{?pg_wrap_004_min_age}
\else
\set pg_wrap_004_min_age 200000000
\endif

-- PG-BAK-011
\if :{?pg_bak_011_duration_seconds}
\else
\set pg_bak_011_duration_seconds 7200
\endif

-- PG-CAP-008
\if :{?pg_cap_008_temp_bytes_per_day}
\else
\set pg_cap_008_temp_bytes_per_day 53687091200
\endif

-- PG-CONN-004
\if :{?pg_conn_004_min_connections}
\else
\set pg_conn_004_min_connections 100
\endif
\if :{?pg_conn_004_idle_fraction}
\else
\set pg_conn_004_idle_fraction 0.80
\endif

-- PG-CONN-005
\if :{?pg_conn_005_sessions_per_second}
\else
\set pg_conn_005_sessions_per_second 10
\endif

-- PG-CONN-006
\if :{?pg_conn_006_abnormal_fraction}
\else
\set pg_conn_006_abnormal_fraction 0.01
\endif
\if :{?pg_conn_006_min_sessions}
\else
\set pg_conn_006_min_sessions 10000
\endif

-- PG-IDX-012
\if :{?pg_idx_012_min_indexes}
\else
\set pg_idx_012_min_indexes 10
\endif
\if :{?pg_idx_012_min_writes}
\else
\set pg_idx_012_min_writes 1000000
\endif

-- PG-LOCK-010
\if :{?pg_lock_010_query_seconds}
\else
\set pg_lock_010_query_seconds 600
\endif

-- PG-MEM-002
\if :{?pg_mem_002_ram_fraction}
\else
\set pg_mem_002_ram_fraction 0.40
\endif
\if :{?pg_mem_002_ram_bytes}
\else
\set pg_mem_002_ram_bytes 0
\endif

-- PG-MEM-004
\if :{?pg_mem_004_work_mem_bytes}
\else
\set pg_mem_004_work_mem_bytes 4194304
\endif
\if :{?pg_mem_004_temp_bytes_per_day}
\else
\set pg_mem_004_temp_bytes_per_day 10737418240
\endif
\if :{?pg_mem_004_temp_files_per_day}
\else
\set pg_mem_004_temp_files_per_day 1000
\endif

-- PG-MEM-005
\if :{?pg_mem_005_maintenance_work_mem_bytes}
\else
\set pg_mem_005_maintenance_work_mem_bytes 67108864
\endif
\if :{?pg_mem_005_total_bytes}
\else
\set pg_mem_005_total_bytes 107374182400
\endif

-- PG-MEM-008
\if :{?pg_mem_008_shared_buffers_bytes}
\else
\set pg_mem_008_shared_buffers_bytes 8589934592
\endif

-- PG-QRY-008
\if :{?pg_qry_008_dominance}
\else
\set pg_qry_008_dominance 0.25
\endif
\if :{?pg_qry_008_min_calls}
\else
\set pg_qry_008_min_calls 1000
\endif

-- PG-QRY-009
\if :{?pg_qry_009_temp_bytes}
\else
\set pg_qry_009_temp_bytes 1073741824
\endif
\if :{?pg_qry_009_top_n}
\else
\set pg_qry_009_top_n 5
\endif

-- PG-QRY-011
\if :{?pg_qry_011_rollback_ratio}
\else
\set pg_qry_011_rollback_ratio 0.10
\endif
\if :{?pg_qry_011_min_transactions}
\else
\set pg_qry_011_min_transactions 10000
\endif

-- PG-QRY-014
\if :{?pg_qry_014_jit_fraction}
\else
\set pg_qry_014_jit_fraction 0.05
\endif

-- PG-REL-003
\if :{?pg_rel_003_eol_days}
\else
\set pg_rel_003_eol_days 180
\endif

-- PG-REL-004
\if :{?pg_rel_004_minors_behind}
\else
\set pg_rel_004_minors_behind 2
\endif

-- PG-REL-014
\if :{?pg_rel_014_errors_per_hour}
\else
\set pg_rel_014_errors_per_hour 100
\endif
\if :{?pg_rel_014_window_hours}
\else
\set pg_rel_014_window_hours 24
\endif

-- PG-SCHEMA-005
\if :{?pg_schema_005_min_bytes}
\else
\set pg_schema_005_min_bytes 214748364800
\endif

-- PG-SCHEMA-006
\if :{?pg_schema_006_min_bytes}
\else
\set pg_schema_006_min_bytes 1073741824
\endif
\if :{?pg_schema_006_parent_fraction}
\else
\set pg_schema_006_parent_fraction 0.10
\endif

-- PG-SCHEMA-013
\if :{?pg_schema_013_min_bytes}
\else
\set pg_schema_013_min_bytes 10737418240
\endif

-- PG-SEC-005
\if :{?pg_sec_005_ssl_fraction}
\else
\set pg_sec_005_ssl_fraction 0.50
\endif

-- PG-VAC-007
\if :{?pg_vac_007_bloat_pct}
\else
\set pg_vac_007_bloat_pct 30
\endif
\if :{?pg_vac_007_wasted_bytes}
\else
\set pg_vac_007_wasted_bytes 209715200
\endif
\if :{?pg_vac_007_bloat_pct_high}
\else
\set pg_vac_007_bloat_pct_high 50
\endif
\if :{?pg_vac_007_wasted_bytes_high}
\else
\set pg_vac_007_wasted_bytes_high 1073741824
\endif
\if :{?pg_vac_007_top_n}
\else
\set pg_vac_007_top_n 10
\endif

-- PG-VAC-008
\if :{?pg_vac_008_total_bytes}
\else
\set pg_vac_008_total_bytes 536870912000
\endif
\if :{?pg_vac_008_cost_delay_ms}
\else
\set pg_vac_008_cost_delay_ms 2
\endif

-- PG-VAC-010
\if :{?pg_vac_010_min_tuples}
\else
\set pg_vac_010_min_tuples 100000000
\endif

-- PG-VAC-011
\if :{?pg_vac_011_cancel_count}
\else
\set pg_vac_011_cancel_count 10
\endif
\if :{?pg_vac_011_window_hours}
\else
\set pg_vac_011_window_hours 24
\endif

-- PG-VAC-013
\if :{?pg_vac_013_min_inserts}
\else
\set pg_vac_013_min_inserts 10000000
\endif

-- PG-WAL-002
\if :{?pg_wal_002_wal_bytes_per_hour}
\else
\set pg_wal_002_wal_bytes_per_hour 1073741824
\endif

-- PG-WAL-007
\if :{?pg_wal_007_full_ratio}
\else
\set pg_wal_007_full_ratio 0.10
\endif
\if :{?pg_wal_007_min_full}
\else
\set pg_wal_007_min_full 100000
\endif

-- PG-WAL-009
\if :{?pg_wal_009_sync_ms}
\else
\set pg_wal_009_sync_ms 5000
\endif
\if :{?pg_wal_009_min_checkpoints}
\else
\set pg_wal_009_min_checkpoints 20
\endif

-- PG-WRAP-008
\if :{?pg_wrap_008_failsafe_age}
\else
\set pg_wrap_008_failsafe_age 1600000000
\endif

-- PG-CAP-007
\if :{?pg_cap_007_min_bytes}
\else
\set pg_cap_007_min_bytes 10737418240
\endif

-- PG-IDX-003
\if :{?pg_idx_003_min_bytes}
\else
\set pg_idx_003_min_bytes 52428800
\endif
\if :{?pg_idx_003_big_bytes}
\else
\set pg_idx_003_big_bytes 1073741824
\endif
\if :{?pg_idx_003_stats_age_days}
\else
\set pg_idx_003_stats_age_days 30
\endif
\if :{?pg_idx_003_top_n}
\else
\set pg_idx_003_top_n 20
\endif

-- PG-IDX-007
\if :{?pg_idx_007_bloat_pct}
\else
\set pg_idx_007_bloat_pct 30
\endif
\if :{?pg_idx_007_wasted_bytes}
\else
\set pg_idx_007_wasted_bytes 104857600
\endif
\if :{?pg_idx_007_bloat_pct_high}
\else
\set pg_idx_007_bloat_pct_high 50
\endif
\if :{?pg_idx_007_wasted_bytes_high}
\else
\set pg_idx_007_wasted_bytes_high 524288000
\endif
\if :{?pg_idx_007_top_n}
\else
\set pg_idx_007_top_n 10
\endif

-- PG-IDX-009
\if :{?pg_idx_009_min_bytes}
\else
\set pg_idx_009_min_bytes 104857600
\endif
\if :{?pg_idx_009_parent_writes}
\else
\set pg_idx_009_parent_writes 1000
\endif
\if :{?pg_idx_009_top_n}
\else
\set pg_idx_009_top_n 20
\endif

-- PG-IDX-011
\if :{?pg_idx_011_min_bytes}
\else
\set pg_idx_011_min_bytes 104857600
\endif
\if :{?pg_idx_011_max_bytes}
\else
\set pg_idx_011_max_bytes 1073741824
\endif
\if :{?pg_idx_011_min_seq_scans}
\else
\set pg_idx_011_min_seq_scans 100
\endif
\if :{?pg_idx_011_rows_per_scan}
\else
\set pg_idx_011_rows_per_scan 100000
\endif
\if :{?pg_idx_011_seq_fraction}
\else
\set pg_idx_011_seq_fraction 0.05
\endif
\if :{?pg_idx_011_top_n}
\else
\set pg_idx_011_top_n 20
\endif

-- PG-IDX-013
\if :{?pg_idx_013_min_bytes}
\else
\set pg_idx_013_min_bytes 1073741824
\endif
\if :{?pg_idx_013_index_multiple}
\else
\set pg_idx_013_index_multiple 2
\endif

-- PG-IDX-014
\if :{?pg_idx_014_min_key_columns}
\else
\set pg_idx_014_min_key_columns 6
\endif
\if :{?pg_idx_014_min_bytes}
\else
\set pg_idx_014_min_bytes 104857600
\endif

-- PG-IDX-015
\if :{?pg_idx_015_max_distinct}
\else
\set pg_idx_015_max_distinct 3
\endif
\if :{?pg_idx_015_min_bytes}
\else
\set pg_idx_015_min_bytes 104857600
\endif

-- PG-IDX-016
\if :{?pg_idx_016_pending_bytes}
\else
\set pg_idx_016_pending_bytes 67108864
\endif
\if :{?pg_idx_016_min_bytes}
\else
\set pg_idx_016_min_bytes 104857600
\endif

-- PG-LOCK-008
\if :{?pg_lock_008_deadlocks_per_day}
\else
\set pg_lock_008_deadlocks_per_day 1
\endif
\if :{?pg_lock_008_min_deadlocks}
\else
\set pg_lock_008_min_deadlocks 7
\endif

-- PG-MEM-007
\if :{?pg_mem_007_storage_class}
\else
\set pg_mem_007_storage_class unknown
\endif

-- PG-MEM-010
\if :{?pg_mem_010_hit_ratio}
\else
\set pg_mem_010_hit_ratio 0.90
\endif
\if :{?pg_mem_010_min_reads}
\else
\set pg_mem_010_min_reads 1000000
\endif

-- PG-QRY-002
\if :{?pg_qry_002_min_dealloc}
\else
\set pg_qry_002_min_dealloc 1000
\endif
\if :{?pg_qry_002_dealloc_per_day}
\else
\set pg_qry_002_dealloc_per_day 100
\endif

-- PG-QRY-010
\if :{?pg_qry_010_top_n}
\else
\set pg_qry_010_top_n 50
\endif

-- PG-QRY-013
\if :{?pg_qry_013_stddev_multiple}
\else
\set pg_qry_013_stddev_multiple 3
\endif
\if :{?pg_qry_013_min_calls}
\else
\set pg_qry_013_min_calls 1000
\endif
\if :{?pg_qry_013_min_mean_ms}
\else
\set pg_qry_013_min_mean_ms 10
\endif
\if :{?pg_qry_013_top_n}
\else
\set pg_qry_013_top_n 10
\endif

-- PG-QRY-016
\if :{?pg_qry_016_min_calls}
\else
\set pg_qry_016_min_calls 1000000
\endif
\if :{?pg_qry_016_rows_per_call}
\else
\set pg_qry_016_rows_per_call 0.01
\endif
\if :{?pg_qry_016_top_n}
\else
\set pg_qry_016_top_n 10
\endif

-- PG-REPL-016
\if :{?pg_repl_016_query_seconds}
\else
\set pg_repl_016_query_seconds 1800
\endif

-- PG-SCHEMA-003
\if :{?pg_schema_003_top_n}
\else
\set pg_schema_003_top_n 10
\endif

-- PG-SCHEMA-007
\if :{?pg_schema_007_max_partitions}
\else
\set pg_schema_007_max_partitions 1000
\endif

-- PG-SCHEMA-009
\if :{?pg_schema_009_min_writes}
\else
\set pg_schema_009_min_writes 1000000
\endif

-- PG-SCHEMA-010
\if :{?pg_schema_010_max_relations}
\else
\set pg_schema_010_max_relations 10000
\endif

-- PG-VAC-012
\if :{?pg_vac_012_min_updates}
\else
\set pg_vac_012_min_updates 1000000
\endif
\if :{?pg_vac_012_hot_ratio}
\else
\set pg_vac_012_hot_ratio 0.10
\endif

-- PG-WAL-003
\if :{?pg_wal_003_target}
\else
\set pg_wal_003_target 0.9
\endif

-- PG-WAL-005
\if :{?pg_wal_005_maxwritten_per_day}
\else
\set pg_wal_005_maxwritten_per_day 1000
\endif

-- PG-WAL-008
\if :{?pg_wal_008_fpi_ratio}
\else
\set pg_wal_008_fpi_ratio 0.3
\endif

-- PG-QRY-003
\if :{?pg_qry_003_top_n}
\else
\set pg_qry_003_top_n 10
\endif

-- PG-QRY-004
\if :{?pg_qry_004_top_n}
\else
\set pg_qry_004_top_n 10
\endif
\if :{?pg_qry_004_min_calls}
\else
\set pg_qry_004_min_calls 100
\endif

-- PG-QRY-005
\if :{?pg_qry_005_top_n}
\else
\set pg_qry_005_top_n 10
\endif

-- PG-QRY-006
\if :{?pg_qry_006_top_n}
\else
\set pg_qry_006_top_n 10
\endif

-- PG-QRY-007
\if :{?pg_qry_007_top_n}
\else
\set pg_qry_007_top_n 10
\endif

-- PG-CAP-005
\if :{?pg_cap_005_top_n}
\else
\set pg_cap_005_top_n 20
\endif

-- PG-INFO-005
\if :{?pg_info_005_top_n}
\else
\set pg_info_005_top_n 10
\endif

-- XX-META-003
\if :{?xx_meta_003_stats_age_seconds}
\else
\set xx_meta_003_stats_age_seconds 86400
\endif

-- XX-META-004
\if :{?xx_meta_004_registry_age_days}
\else
\set xx_meta_004_registry_age_days 365
\endif
\if :{?xx_meta_004_versions_age_days}
\else
\set xx_meta_004_versions_age_days 180
\endif

-- XX-META-007
\if :{?xx_meta_007_max_databases}
\else
\set xx_meta_007_max_databases 5
\endif
\if :{?xx_meta_007_max_relations}
\else
\set xx_meta_007_max_relations 50000
\endif

-- XX-META-008
\if :{?xx_meta_008_answer_age_days}
\else
\set xx_meta_008_answer_age_days 180
\endif

\echo '@@RUN-BEGIN deep database'
SELECT '@@TARGET ' || current_database() || ' ' || current_setting('server_version') || ' ' || CASE WHEN pg_is_in_recovery() THEN 'standby' ELSE 'primary' END AS t \gset qq_
\echo :qq_t

\echo '@@RUN-END deep database'
