-- check: MY-IDX-003
-- title: Redundant or duplicate indexes
-- priority: 50 | category: IDX | scope: index | cost: 1 | pass: fast
-- engine: mysql,mariadb | requires: (none)
-- thresholds: (none)
-- reads: sys.schema_redundant_indexes, or an information_schema.STATISTICS
--        self-join where sys is absent
-- Availability, verified on MariaDB 10.11: sys.schema_redundant_indexes exists
-- on MySQL 5.7+ and MariaDB 10.6+ with identical columns, including the
-- ready-made sql_drop_index text. The fallback reproduces the leftmost-prefix
-- comparison directly from information_schema.STATISTICS by building each
-- index's ordered column list and testing prefix containment.
-- Unlike MY-IDX-001 this needs no usage statistics and carries no per-instance
-- caveat: an index that is a strict leftmost prefix of another is redundant as a
-- matter of B-tree structure, on every replica, forever. Any query the prefix
-- index can serve, the longer index can serve at the same cost.
-- The exception the check respects: a UNIQUE index is never redundant to a
-- non-unique one, because it also enforces a constraint.
SET @dbt_q_sys := "
SELECT
  'MY-IDX-003' AS check_id,
  'index'      AS scope,
  CONCAT(r.table_schema, '.', r.table_name, '.', r.redundant_index_name) AS object,
  CONCAT('Index `', r.redundant_index_name, '` (', r.redundant_index_columns,
         ') on `', r.table_schema, '`.`', r.table_name,
         '` is redundant: `', r.dominant_index_name, '` (', r.dominant_index_columns,
         ') already covers it. ',
         IF(r.subpart_exists = 1,
            'NOTE: one of these uses a column prefix (a partial index), so confirm the covering claim before dropping. ', ''),
         'This is structural, not statistical — it holds on every replica and does not depend on workload, so unlike MY-IDX-001 it needs no per-replica verification. ',
         'The redundant index still costs a write on every INSERT, UPDATE and DELETE to the table and consumes buffer pool space. ',
         'Drop statement generated by the sys schema: ', r.sql_drop_index) AS details,
  JSON_OBJECT(
    'schema', r.table_schema, 'table', r.table_name,
    'redundant_index', r.redundant_index_name, 'redundant_columns', r.redundant_index_columns,
    'dominant_index', r.dominant_index_name, 'dominant_columns', r.dominant_index_columns,
    'redundant_is_non_unique', r.redundant_index_non_unique,
    'dominant_is_non_unique', r.dominant_index_non_unique,
    'has_column_prefix', r.subpart_exists,
    'drop_statement', r.sql_drop_index) AS evidence_json,
  'high' AS confidence
FROM sys.schema_redundant_indexes AS r
WHERE r.table_schema NOT IN ('mysql', 'information_schema', 'performance_schema', 'sys')
ORDER BY r.table_schema, r.table_name
LIMIT 50";

SET @dbt_q_fb := "
SELECT
  'MY-IDX-003' AS check_id,
  'index'      AS scope,
  CONCAT(a.sch, '.', a.tbl, '.', a.idx) AS object,
  CONCAT('Index `', a.idx, '` (', a.cols, ') on `', a.sch, '`.`', a.tbl,
         '` is a leftmost prefix of `', b.idx, '` (', b.cols,
         '), so it is redundant. Computed from information_schema.STATISTICS because this server has no sys schema. ',
         'This is structural and holds on every replica. The redundant index still costs a write on every modification of the table. ',
         'Drop with: ALTER TABLE `', a.sch, '`.`', a.tbl, '` DROP INDEX `', a.idx, '`;') AS details,
  JSON_OBJECT(
    'schema', a.sch, 'table', a.tbl,
    'redundant_index', a.idx, 'redundant_columns', a.cols,
    'dominant_index', b.idx, 'dominant_columns', b.cols,
    'source', 'information_schema.STATISTICS fallback') AS evidence_json,
  'medium' AS confidence
FROM (
  SELECT TABLE_SCHEMA AS sch, TABLE_NAME AS tbl, INDEX_NAME AS idx,
         MIN(NON_UNIQUE) AS non_unique,
         GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') AS cols
    FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA NOT IN ('mysql', 'information_schema', 'performance_schema', 'sys')
   GROUP BY TABLE_SCHEMA, TABLE_NAME, INDEX_NAME
) AS a
JOIN (
  SELECT TABLE_SCHEMA AS sch, TABLE_NAME AS tbl, INDEX_NAME AS idx,
         MIN(NON_UNIQUE) AS non_unique,
         GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') AS cols
    FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA NOT IN ('mysql', 'information_schema', 'performance_schema', 'sys')
   GROUP BY TABLE_SCHEMA, TABLE_NAME, INDEX_NAME
) AS b
  ON b.sch = a.sch AND b.tbl = a.tbl AND b.idx <> a.idx
WHERE a.idx <> 'PRIMARY'
  AND a.non_unique = 1
  AND (b.cols = a.cols OR b.cols LIKE CONCAT(a.cols, ',%'))
  AND (b.cols <> a.cols OR a.idx > b.idx)
LIMIT 50";

SET @dbt_q := IF(IFNULL(@dbt_sys_redundant_idx, 0) = 1, @dbt_q_sys, @dbt_q_fb);
PREPARE dbt_stmt FROM @dbt_q; EXECUTE dbt_stmt; DEALLOCATE PREPARE dbt_stmt;
